version: '3'

services:
  redis:
    image: redis
    ports:
      - '6379:6379'
    networks:
      - redis-network
    command: redis-server --requirepass PC1112131415
  db:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    networks:
      - redis-network
    volumes:
      - ./database:/var/lib/postgresql/data
  app:
    build: .
    command: >
      bash -c "yarn typeorm migration:run
      && yarn start:dev"
    networks:
      - redis-network
    ports:
      - '3000:3000'
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
networks:
  redis-network:
    driver: bridge
